export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAIL = 'GET_USER_FAIL'

export const SET_USER = 'SET_USER'
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS'
export const SET_USER_FAIL = 'SET_USER_FAIL'

export const GET_USERLIST = 'GET_USERLIST'
export const GET_USERLIST_SUCCESS = 'GET_USERLIST_SUCCESS'
export const GET_USERLIST_FAIL = 'GET_USERLIST_FAIL'

export const CHECK_IN_USER = 'CHECK_IN_USER'
export const CHECK_IN_USER_SUCCESS = 'CHECK_IN_USER_SUCCESS'
export const CHECK_IN_USER_FAIL = 'CHECK_IN_USER_FAIL'

export const USER_SEARCH = 'USER_SEARCH'
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS'
export const USER_SEARCH_FAIL = 'USER_SEARCH_FAIL'

export const REHYDRATE_TOKEN = 'REHYDRATE_TOKEN'
export const LOGOUT = 'LOGOUT'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const CLEAR_FOUND_USER = 'CLEAR_FOUND_USER'
